name: deploy

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'          # ✅ Upgrade Ruby so uri >= 1.0 ships by default
        bundler-cache: true

    - name: Update Bundler
      run: gem install bundler       # ✅ Ensure latest bundler

    - name: Install deps
      run: |
        npm install -g @mermaid-js/mermaid-cli   # ✅ use maintained mermaid-cli fork

    - name: Setup deploy options
      id: setup
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

        if [[ ${GITHUB_REF} = refs/pull/*/merge ]]; then # pull request
          echo "SRC_BRANCH=${GITHUB_HEAD_REF}" >> $GITHUB_OUTPUT
          echo "NO_PUSH=--no-push" >> $GITHUB_OUTPUT
        elif [[ ${GITHUB_REF} = refs/heads/* ]]; then # branch, e.g. master, source etc
          echo "SRC_BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
        fi
        echo "DEPLOY_BRANCH=gh-pages" >> $GITHUB_OUTPUT

    - name: Deploy website
      run: |
        yes | bash bin/deploy --verbose \
          ${{ steps.setup.outputs.NO_PUSH }} \
          --src ${{ steps.setup.outputs.SRC_BRANCH }} \
          --deploy ${{ steps.setup.outputs.DEPLOY_BRANCH }}
